import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";
import { Button } from "react-bootstrap";
import Modal from "react-bootstrap/Modal";

const inter = Inter({ subsets: ["latin"] });

export default function Otherform() {
  const [show, setShow] = useState(false);
  const handleClose = () => setShow(false);
  const handleShowTwo = () => {
    setShow(true)
  }
  return (
    <>
      <Head>
        <title>Other Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
        <div className="d-flex justify-content-end">
        <button className={styles.addbtn} onClick={handleShowTwo}>Add New</button>
        </div>
        <Modal show={show} onHide={handleClose}>
                   
                  
                   <Modal.Body>
                       <h6 className={styles.forgotpassword}>Change Password</h6>
                       <div className={styles.forgotcontainer}>
                       <div className={styles.forgottexts}>
                         Kindly create a new password for yourself
                       </div>
                       
                         <div className={styles.modalsubtext}>
                           <label className="d-flex">New Password</label>
                           <div className={styles.forgotInputContainer}>
                             <input
                               type= "text" 
                               placeholder="title"
                               name="password"
                              //  value={keywords.title}
                              //  onChange={handleChange}
                               className={`${styles.passwordinput} form-contol`}
                             />
                            
                           </div>
                         </div>
                         <div className={styles.modalsubtext}>
                         <label className="d-flex">Confirm New Password</label>
                           <div className={styles.forgotInputContainer}>
                             <input
                               type= "text"
                               placeholder="slug"
                               name="password"
                              //  value={keywords.slug}
                              //  onChange={handleChange}
                               className={`${styles.passwordinput} form-contol`}
                             />
                             
                           </div>
                         </div>
                         <div className={styles.modalsubtext}>
                         <label className="d-flex">Limit</label>
                           <div className={styles.forgotInputContainer}>
                             <input
                               type= "number"
                               placeholder="limit"
                               name="password"
                              //  value={keywords.limit}
                              //  onChange={handleChange}
                               className={`${styles.passwordinput} form-contol`}
                             />
                             
                           </div>
                         </div>
                       </div>
                     </Modal.Body>
                    
                     <div className={`${styles.confirmbtn} mb-5 py-1`}>
                       
                      
                       <Button
                      //  onClick={AddNewKeyword}
                         className={`${styles.passwordcontinue} d-flex justify-content-center align-items-center`}
                       >
                         Submit
                       </Button>
                     </div>
                   </Modal>
        </div>
        
      </main>
    </>
  );
}
